name: clothing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_dino: ^1.0.1+3
  flutter_local_notifications: ^20.0.0
  intl: ^0.20.2
  flutter_spinkit: ^5.2.2
  bubble: ^1.2.1
  image_picker: ^1.2.1
  flutter_native_contact_picker: ^0.0.11
  permission_handler: ^12.0.1
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  just_audio: ^0.10.5
  audioplayers: ^6.5.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - .env


