name: clothing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_dino: ^1.0.1+3
  flutter_local_notifications: ^20.0.0
  intl: ^0.20.2
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - .env


